name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy para Render
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy no Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"